# Generated by Django 3.2.9 on 2021-11-27 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_message_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='task_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.task', verbose_name='task'),
        ),
    ]
