# Generated by Django 3.2.9 on 2021-11-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_message_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='task_to',
            new_name='task',
        ),
    ]
